src/Entity/ProductVariant.php
<?php

namespace App\Entity;

use App\Repository\ProductVariantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductVariantRepository::class)]
class ProductVariant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $size = null;

    /**
     * @var Collection<int, Taxe>
     */
    #[ORM\OneToMany(targetEntity: Taxe::class, mappedBy: 'productVariant_id')]
    private Collection $taxe_id;

    #[ORM\ManyToOne(inversedBy: 'productVariants')]
    private ?Product $product_id = null;

    public function __construct()
    {
        $this->taxe_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getSize(): ?float
    {
        return $this->size;
    }

    public function setSize(float $size): static
    {
        $this->size = $size;

        return $this;
    }

    /**
     * @return Collection<int, Taxe>
     */
    public function getTaxeId(): Collection
    {
        return $this->taxe_id;
    }

    public function addTaxeId(Taxe $taxeId): static
    {
        if (!$this->taxe_id->contains($taxeId)) {
            $this->taxe_id->add($taxeId);
            $taxeId->setProductVariantId($this);
        }

        return $this;
    }

    public function removeTaxeId(Taxe $taxeId): static
    {
        if ($this->taxe_id->removeElement($taxeId)) {
            // set the owning side to null (unless already changed)
            if ($taxeId->getProductVariantId() === $this) {
                $taxeId->setProductVariantId(null);
            }
        }

        return $this;
    }

    public function getProductId(): ?Product
    {
        return $this->product_id;
    }

    public function setProductId(?Product $product_id): static
    {
        $this->product_id = $product_id;

        return $this;
    }
}

templates/Components/_deliveryCard.html.twig
<div>
	<div>
		<em>{{ delivery.name }}</em>
	</div>
		<div>
		<em>{{ delivery.description }}</em>
	</div>
		<div>
		<em>{{ delivery.price }}</em>
	</div>
	<div>
		<em>{{ delivery.enable }}</em>
	</div>
	<div>
		<a href="{{ path('admin.delivery.update', {id: delivery.id }) }}" class="">Update</a>
	</div>
	<form method="POST" action="{{ path('admin.delivery.delete', {id: delivery.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir supprimer ( {{ delivery.name }} ) ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ delivery.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>

templates/Components/_genderCard.html.twig
<div>
	<div>
		<em>{{ gender.name }}</em>
	</div>
	<div>
		<em>{{ gender.enable }}</em>
	</div>
	<div>
		<a href="{{ path('admin.gender.update', {id: gender.id }) }}" class="">Update</a>
	</div>
	<form method="POST" action="{{ path('admin.gender.delete', {id: gender.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir supprimer ( {{ gender.name }} ) ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ gender.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>

templates/Components/_marqueCard.html.twig
<div>
	<div>
		<em>{{ marque.name }}</em>
	</div>

	<div>
		<em>{{ marque.slug }}</em>
	</div>

	<div>
		<em>{{ marque.description }}</em>
	</div>

	<div>
		<em>{{ marque.imageName }}</em>
	</div>

	<div>
		<em>{{ marque.enable }}</em>
	</div


	<div>
		<a href="{{ path('admin.marque.update', {id: marque.id }) }}" class="">Update</a>
	</div>
	<form method="POST" action="{{ path('admin.marque.delete', {id: marque.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir supprimer ( {{ marque.name }} ) ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ marque.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>

templates/Components/_modelCard.html.twig
<div>
	<div>
		<em>{{ model.name }}</em>
	</div>

	<div>
		<em>{{ model.slug }}</em>
	</div>

	<div>
		<em>{{ model.enable }}</em>
	</div>
	<div>
		<a href="{{ path('admin.model.update', {id: model.id }) }}" class="">Update</a>
	</div>
	<form method="POST" action="{{ path('admin.model.delete', {id: model.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir supprimer ( {{ model.name }} ) ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ model.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>

templates/Components/_productImageCard.html.twig
<div>
	<div>
		<em>{{ productImage.imageName }}</em>
	</div>

	<div>
		<em>{{ productImage.imageSize }}</em>
	</div>

	<div>
		<em>{{ productImage.product.name }}</em>
	</div>

	<div>
		<a href="{{ path('admin.productimage.update', {id: productImage.id }) }}" class="">Update</a>
	</div>

	<form method="POST" action="{{ path('admin.productimage.delete', {id: productImage.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir de la supprimer ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ productImage.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>

templates/Components/_productVariantCard.html.twig
<div>
	<div>
		<em>{{ productVariant.price }}</em>
	</div>
	<div>
		<em>{{ productVariant.size }}</em>
		<div>
			<em>{{ productVariant.productId.name }}</em>
		</div>
		<div>
			<a href="{{ path('admin.productvariant.update', {id: productVariant.id }) }}" class="">Update</a>
		</div>
		<form method="POST" action="{{ path('admin.productvariant.delete', {id: productVariant.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir le supprimer ?')">
			<input type="hidden" name="_method" value="DELETE">
			<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ productVariant.id) }}">
			<button class="">Supprimer</button>
		</form>
		<br>


	</div>

templates/Components/_pruduitCard.html.twig
<div>
	<div>
		<em>{{ product.name }}</em>
	</div>
	<div>
		<em>{{ product.description }}</em>
	</div>
	<div>
		<em>{{ product.enable }}</em>
	</div>
	<div>
		<a href="{{ path('admin.product.update', {id: product.id }) }}" class="">Update</a>
	</div>
	<form method="POST" action="{{ path('admin.product.delete', {id: product.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir supprimer ( {{ product.name }} ) ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>

templates/Components/_taxeCard.html.twig
<div>
	<div>
		<em>{{ taxe.name }}</em>
	</div>
		<div>
		<em>{{ taxe.rate }}</em>
	<div>
		<em>{{ taxe.enable }}</em>
	</div>
	<div>
		<a href="{{ path('admin.taxe.update', {id: taxe.id }) }}" class="">Update</a>
	</div>
	<form method="POST" action="{{ path('admin.taxe.delete', {id: taxe.id}) }}" onsubmit="return confirm('Êtes-vous sùr de vouloir supprimer ( {{ taxe.name }} ) ?')">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ taxe.id) }}">
		<button class="">Supprimer</button>
	</form>
	<br>


</div>